# Generated by Django 4.2.29 on 2026-03-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='e.g. Piso 1', max_length=255)),
                ('nivel', models.IntegerField(default=1, help_text='Floor level number')),
                ('imagen', models.ImageField(upload_to='planos/')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='inventory.recinto')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('anydesk', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_texto', models.CharField(blank=True, help_text='Ubicación original del CSV', max_length=255, null=True)),
                ('coord_x', models.FloatField(blank=True, help_text='X coordinate on the image (CRS.Simple)', null=True)),
                ('coord_y', models.FloatField(blank=True, help_text='Y coordinate on the image (CRS.Simple)', null=True)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventory.plano')),
            ],
        ),
    ]
