# Generated by Django 4.2.29 on 2026-03-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_activo_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.RemoveField(
            model_name='activo',
            name='password',
        ),
        migrations.AddField(
            model_name='activo',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Almacenamiento/Tipo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ant_centro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ant. Centro'),
        ),
        migrations.AddField(
            model_name='activo',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='activo',
            name='contrasena_wifi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña WiFi'),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_instalacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha Instalación'),
        ),
        migrations.AddField(
            model_name='activo',
            name='key_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Licencia Office'),
        ),
        migrations.AddField(
            model_name='activo',
            name='licencia_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Licencia Office'),
        ),
        migrations.AddField(
            model_name='activo',
            name='mac_managerlab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC ManagerLab'),
        ),
        migrations.AddField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N° Serie'),
        ),
        migrations.AddField(
            model_name='activo',
            name='pass_anydesk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pass AnyDesk'),
        ),
        migrations.AddField(
            model_name='activo',
            name='pass_managerlab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pass ManagerLab'),
        ),
        migrations.AddField(
            model_name='activo',
            name='pass_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pass Office'),
        ),
        migrations.AddField(
            model_name='activo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='activo',
            name='version_win',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Versión Windows'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='anydesk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID AnyDesk'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='coord_x',
            field=models.FloatField(blank=True, help_text='Coordenada X en la imagen (CRS.Simple)', null=True, verbose_name='Coord X'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='coord_y',
            field=models.FloatField(blank=True, help_text='Coordenada Y en la imagen (CRS.Simple)', null=True, verbose_name='Coord Y'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP/Red WiFi'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventory.plano', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RAM/Tipo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación (CSV)'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuario'),
        ),
    ]
