# Generated by Django 4.2.29 on 2026-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_activo_options_remove_activo_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiqueta'),
        ),
    ]
